server:
  port: 9090
  servlet:
    context-path: /bykerack

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bykerack
    username: sa
    password: cptm
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

cptm:
  jwt:
    expiration: 900000
  jwk:
    jks-file: cptmtoken.jks
    password:
      key-store: default
      key-pass: default
    alias: cptmtoken
  cors:
    allowed-origins: http://localhost:9091, http://localhost:8081