server:
  port: 9090
  servlet:
    context-path: /bykerack

spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: ${ORACLE_CONNECTION_STRING}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

cptm:
  jwt:
    expiration: 900000
  jwk:
    jks-file: /home/cptmtoken.jks
    password:
      key-store: ${JKS_STORE_PASS}
      key-pass: ${JKS_KEY_PASS}
    alias: cptmtoken
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
