INSERT INTO DOCUMENT_TYPE(NAME) VALUES('RG');
INSERT INTO DOCUMENT_TYPE(NAME) VALUES('CPF');
INSERT INTO DOCUMENT_TYPE(NAME) VALUES('CTPS');
INSERT INTO DOCUMENT_TYPE(NAME) VALUES('CNH');

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 7 - Rubi', '#A8034F');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Vila Aurora', 1, 144, 'Vila Aurora');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Franco da Rocha', 1, 180, 'Franco da Rocha');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Caieiras', 1, 65, 'Caieiras');

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 10 - Turquesa', '#00879B');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Tamanduateí', 2, 164, 'Tamanduateí');

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 11 - Coral', '#F55F1A');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Ferraz de Vasconcelos', 3, 136, 'Ferraz de Vasconcelos');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Suzano', 3, 576, 'Suzano');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Poá', 3, 60, 'Poá');

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 12 - Safira', '#1C1468');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Calmon Viana', 4, 84, 'Calmon Viana');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Comendador Ermelino', 4, 196, 'Comendador Ermelino');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Itaim Paulista', 4, 256, 'Itaim Paulista');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Jardim Helena', 4, 256, 'Jardim Helena');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Jardim Romano', 4, 240, 'Jardim Romano');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Eng. Manoel Feio', 4, 282, 'Eng. Manoel Feio');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('USP Leste', 4, 270, 'USP Leste');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('São Miguel Paulista', 4, 208, 'São Miguel Paulista');

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 13 - Jade', '#00AA9E');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Engenheiro Goulart - Norte', 5, 200, 'Engenheiro Goulart');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Engenheiro Goulart - Sul', 5, 74, 'Engenheiro Goulart');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Guarulhos-CECAP', 5, 192, 'Guarulhos-CECAP');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE, VACANCIES, STATION) VALUES('Aeroporto-Guarulhos', 5, 100, 'Aeroporto-Guarulhos');