INSERT INTO DOCUMENT_TYPE(NAME) VALUES('RG');
INSERT INTO DOCUMENT_TYPE(NAME) VALUES('CPF');
INSERT INTO DOCUMENT_TYPE(NAME) VALUES('CTPS');
INSERT INTO DOCUMENT_TYPE(NAME) VALUES('CNH');

INSERT INTO ACCESS(EMAIL, PASSWORD) VALUES('hg570@email.com', '$2a$10$Xuh6Ujd3QZJp81jVOdGdY.s24vDfom7g1TX55umnTRRUPj4F8AbZO');
INSERT INTO USERS(NAME, BIRTH_DATE, DOCUMENT_TYPE_ID, DOCUMENT, ROLE, ACCESS_ID) VALUES('Rafael Pinheiro', '2003-10-10', 1, '536167584', 'EMPLOYEE', 1);

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 7 - Rubi', '#A8034F');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Vila Aurora', 1, 144, 144);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Franco da Rocha', 1, 180, 180);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Caieiras', 1, 65, 65);
INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 10 - Turquesa', '#00879B');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Tamanduateí', 2, 164, 164);

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 11 - Coral', '#F55F1A');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Ferraz de Vasconcelos', 3, 136, 136);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Suzano', 3, 576, 576);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Poá', 3, 60, 60);

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 12 - Safira', '#1C1468');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Calmon Viana', 4, 84, 84);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Comendador Ermelino', 4, 196, 196);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Itaim Paulista', 4, 256, 256);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Jardim Helena', 4, 256, 256);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Jardim Romano', 4, 240, 240);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Eng. Manoel Feio', 4, 282, 282);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('USP Leste', 4, 270, 270);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('São Miguel Paulista', 4, 208, 208);

INSERT INTO RAILWAY_LINE(NAME, COLOR) VALUES('Linha 13 - Jade', '#00AA9E');
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Engenheiro Goulart - Norte', 5, 200, 200);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Engenheiro Goulart - Sul', 5, 74, 74);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Guarulhos-CECAP', 5, 192, 192);
INSERT INTO BIKE_RACK(NAME, RAILWAY_LINE_ID, VACANCIES, AVAILABLE_VACANCIES) VALUES('Aeroporto-Guarulhos', 5, 100, 100);